### PR TITLE
Cleanup and reason behind advertising

### PR DESCRIPTION
**Pull request by richiksc**
I did some basic cleanup (such as rename `gems` to `plugins` in `_config.yml` to deal with Jekyll warnings) as well as add some tooltips on why ads are needed.

### CODE REVIEW

**Comment by richiksc** [comment]
Oops, one more fix.

**Comment by richiksc** [comment]
Ok, fixed. The configurator styles have been moved into a different branch.

**Comment by mfonville** [comment]
Thanks very much for this PR! I will merge it through some rebasing :-)

**Comment by mfonville** [comment]
https://github.com/opengapps/opengapps.github.io/commit/335649bd667ea464ba37a344adb83a5d1c983706

**Comment by richiksc** [comment]
By the way, the changes have been tested on Chrome 59 (Windows 10) and Chrome 59 Mobile (Android 7.1.2, Nexus 5X).

**Pull request closed without merging**
