### PR TITLE
SourceForge migration

### PR DESCRIPTION
**Pull request by nezorflame**
- Code refactoring
- "Beautification"
- Transfer the files to the SourceForge
- Use our [own API](https://github.com/opengapps/package-api) as the backend to support new storage scheme

### CODE REVIEW

**Comment by agateau-g** [comment]
Thanks for taking care of Genymotion links! :+1:

**Comment by agateau-g** [comment]
Just ran a test on genymotion.json, and those urls are 404:
- https://master.dl.sourceforge.net/project/opengapps/x86/20190221/open_gapps-x86-8.0-pico-20190221.zip
- https://master.dl.sourceforge.net/project/opengapps/x86/20190221/open_gapps-x86-9.0-pico-20190221.zip

Looks like those files are missing here: https://sourceforge.net/projects/opengapps/files/x86/20190221/.

Do you plan to add them or do you prefer if I file a PR to point to other versions?

**Comment by nezorflame** [comment]
Oh. Thanks for reporting this. That's my fault, I've synced them manually
and it seems that I've missed these ones.
I'll add them in 1-2 hours.

**Comment by agateau-g** [comment]
Great! Thanks!

**Comment by nezorflame** [comment]
@agateau-g please check again - should be working now.

**Comment by agateau-g** [comment]
All good! :+1:

**Pull request merged**
