### PR TITLE
Add support for Android 11.0 for Genymotion PaaS

### PR DESCRIPTION
**Pull request by JulienBolard**
Hi @mfonville

I hope you're well.
New version supported now. Thanks for adding Android 11.0 to the list of Opengapps packages.

Thanks,
Julien

### CODE REVIEW

**Comment by JulienBolard** [comment]
Hi @mfonville,

Can we merge this one, as we are ready to push in production our Android 11 version pointing to this url?

Best regards,
Julien

**Comment by mfonville** [comment]
Yes, thanks for the heads-up, it is merged!

**Comment by JulienBolard** [comment]
Thank you !

**Comment by MSDarwish2000** [comment]
I can see that in the edit history there is a mention of 

j`ava.lang.NoSuchFieldException: No field isCarrierAp in class Landroid/net/wifi/ScanResult`

Please could you tell me the fix or is it a known bug as I get this exact exception when trying to manually add it to another x86_64 emulator (not Genymotion).

**Comment by gumbarros** [comment]
> I can see that in the edit history there is a mention of
> 
> j`ava.lang.NoSuchFieldException: No field isCarrierAp in class Landroid/net/wifi/ScanResult`
> 
> Please could you tell me the fix or is it a known bug as I get this exact exception when trying to manually add it to another x86_64 emulator (not Genymotion).

This exception also happens on a patched Windows Subsystem for Android with GApps, this is the only place in entire Google with this exception. This exception appears on my Android Studio debugging a app inside WSA.

**Pull request merged**
