### PR TITLE
Clean up Javascript code

### PR DESCRIPTION
**Pull request by sigv**
The Javascript code needs cleaning and additional minor touches could be added, which this change aims to fix. Simple as that.

### CODE REVIEW

**Comment by mfonville** [comment]
Thanks for your PR.
I will study your changes, since I also have some local changes that are ready to published when an external dependency is done :-)
I will try to 3-way merge them.

**Comment by sigv** [comment]
If you want, I can manually rebase this and have the change be a ff. Up to you.

**Comment by mfonville** [comment]
I will manage :)

**Comment by sigv** [comment]
Awesome. Thank you!

**Comment by mfonville** [comment]
I will compress btw some of the javascript again (I know it is less readable) but the more compact gives us faster load time and better ranking :)

**Comment by sigv** [comment]
Yeah, for sure. Feel free to do that post-merge then.. or if possible, tie it in with Jekyll somehow? Like, if the file can be stored expanded and then compressed during site generation? Not sure if it's possible or worth it, but I think it would be nice to have as the file would stay expanded like this then.

**Comment by mfonville** [comment]
I will check that out if it possible in Jekyll, that would indeed be a useful feature :)

UPDATE: they exist but are not part of gh-pages :-(

**Comment by sigv** [comment]
How come this PR was closed?

**Comment by mfonville** [comment]
I have it merged locally and will push it when I the external dependency is fulfilled :-)
Don't worry ;-) and your work is much appreciated

**Comment by sigv** [comment]
Awesome. ETA? 😅

**Comment by mfonville** [comment]
A few days

**Comment by sigv** [comment]
Great! Can't wait.

**Comment by sigv** [comment]
_Looks around and fades back into the darkness of waiting_

**Comment by mfonville** [comment]
@sigv "external" dependency he, if I could make it go faster... :-O

**Pull request closed without merging**
